### PR TITLE
Added a password style in some serializers

### PR DESCRIPTION
**Pull request by Hamza5**
Added `style={'input_type': 'password'}` in the CharFields that are used for passwords, in order to have a correct look in the browsable API.

### CODE REVIEW

**Comment by iMerica** [comment]
Is this for styling in the docs?

**Comment by Hamza5** [comment]
> 
> 
> Is this for styling in the docs?

Yes, it is for obfuscating the passwords while being typed on the Rest Framework Browsable API. It may also have other effects related to passwords. Anyway, as far as I know, all `serializers.CharField`s that are used for passwords should use this styling.

**Comment by iMerica** [comment]
Thanks for your PR and I can see how it would be useful in some cases, but as a whole I think it's outside of scope. DRF API docs are not meant to be a real world UI/client for your API and its not the role of a headless authentication tool to dictate the presentation of passwords in your UI. The UI is a completely separate concern from this package.

**Comment by iMerica** [comment]
Closing this one, but you can definitely get the desired behavior you're looking for by overriding serializers in the `REST_AUTH_SERIALIZERS` settings. Thank you.

**Pull request closed without merging**
