### PR TITLE
Make verify email browsable

### PR DESCRIPTION
**Pull request by brunomichetti**
Verify email was not browsable. get function added in order to solve that.
Fix issue: https://github.com/Tivix/django-rest-auth/issues/558

### CODE REVIEW

**Comment by iMerica** [comment]
Hi @brunomichetti,

I'm confused. The title of this PR is "Make verify email browsable", but the code change raises  `MethodNotAllowed('GET')`, which would make it NOT browsable. What am I missing?

**Comment by brunomichetti** [comment]
> Hi @brunomichetti,
> 
> I'm confused. The title of this PR is "Make verify email browsable", but the code change raises `MethodNotAllowed('GET')`, which would make it NOT browsable. What am I missing?

Hello @iMerica thanks for the review!

When you develop, you should be able to test manually the `registration/verify-email/` endpoint. Right now, if you go to that endpoint, this error raises:

Screen Shot 2020-06-03 at 10 50 42

Whit the fix I added, you can now use the browser to test it manually. You will see something like this:

Screen Shot 2020-06-03 at 11 01 52

Sorry maybe I should add this image when I created the PR.
The `Method not allowed` is because the GET method shouldn't be available to that endpoint.
Let me know any other question you may have.
Thanks!

**Comment by brunomichetti** [comment]
> > Hi @brunomichetti,
> > I'm confused. The title of this PR is "Make verify email browsable", but the code change raises `MethodNotAllowed('GET')`, which would make it NOT browsable. What am I missing?
> 
> Hello @iMerica thanks for the review!
> 
> When you develop, you should be able to test manually the `registration/verify-email/` endpoint. Right now, if you go to that endpoint, this error raises:
> 
> Screen Shot 2020-06-03 at 10 50 42
> 
> With the fix I added, you can now use the browser to test it manually. You will see something like this:
> 
> Screen Shot 2020-06-03 at 11 01 52
> 
> Sorry maybe I should have added this image when I created the PR.
> The `Method not allowed` is because the GET method shouldn't be available for that endpoint.
> Let me know any other question you may have.
> Thanks!

PS: Now obviously you can test it manually but without the browser.

**Comment by iMerica** [comment]
Thanks for the clarification 👍

**Pull request merged**
