### PR TITLE
Add support for Refresh Token Cookie

### PR DESCRIPTION
**Pull request by Wolf-Byte**
Whilst using dj-rest-auth I was struggling to securely store users refresh tokens. I am developing my app in JS so only have Cookies, Local Storage & Session Storage available. Out of the three the only place, I would want to store my tokens would be in HttpOnly Cookies. Out of the box dj-rest-auth supports Token Cookies so I just followed the same pattern used and added Refresh Token Cookies.

There are two new settings for the Refresh Token:

JWT_AUTH_REFRESH_COOKIE
This is the name of the cookie that will store the refresh token

JWT_AUTH_REFRESH_COOKIE_PATH
This is the path set within the cookie, this stops the cookie from being sent with every request.
e.g. only /dj-rest-auth/token/refresh

In addition to the Refresh Cookie, the PR also includes a feature that allows users to return the token and refresh token expiry times. This is helpful as it allows the client to know when tokens are set to expire without disabling HttpOnly on the Cookies.

Setting:
JWT_AUTH_RETURN_EXPIRATION

This is my first PR so please let me know how I can improve any future requests.

If you would like an example of the middleware used so SimpleJWT can access the Token and RefreshToken on calls like /token/verify/ & /token/refresh/ I can provide the classes. In short, the middleware gets the cookie and adds it to the body so SimpleJWT can access it. This is needed because SimpleJWT only supports token and refresh in the body and not as cookies which is not ideal.

### CODE REVIEW

**Comment by iMerica** [comment]
Hi @Wolf-Byte, 

Thanks for submitting this one! I'm going to have a look - hopefully we can merge it by the end of the weekend.

**Comment by Wolf-Byte** [comment]
Thanks @iMerica 

After submitting the pull request I realised the endpoint /token/refresh/ is pretty useless when storing tokens in the HttpOnly Cookies as the endpoint returns the token and doesn't update the cookie.

To get around this I have created a view that extends TokenRefreshView. The view sets the cookie and returns the expiry date in addition to the original data 'refresh'.

Please let me know how you would like me to include this, shall I create a PR after you do the merge or should I just create a new PR with all of the changes in one request?

**Comment by Wolf-Byte** [comment]
Here is the code for the /token/refresh/ I realised as the class extends a SimpleJWT class it makes SimpleJWT a dependency which is not what you want.

Maybe you could have a think about a solution.

Getting this right will be great for the community as I know this functionality is heavily desired in SimpleJWT, there has been an outstanding PR for a while and the repo owner has been super busy with work. TBH it looks like the project could be taken over or Forked (it was mentioned in one of the DjangoChat podcasts).

Here is the PR if you wanted to take a look at the discussion.

Back to the code here is the views.py

`from django.conf import settings
from datetime import datetime

from rest_framework_simplejwt.settings import api_settings as jwt_settings
from rest_framework_simplejwt.views import TokenRefreshView


class CustomTokenRefreshView(TokenRefreshView):
    def post(self, request, *args, **kwargs):
        response = super(TokenRefreshView, self).post(request, *args, **kwargs)

        if response.status_code == 200 and 'refresh' in request.data:
            cookie_name = getattr(settings, 'JWT_AUTH_COOKIE', None)
            cookie_secure = getattr(settings, 'JWT_AUTH_SECURE', False)
            cookie_httponly = getattr(settings, 'JWT_AUTH_HTTPONLY', True)
            cookie_samesite = getattr(settings, 'JWT_AUTH_SAMESITE', 'Lax')

            token_expiration = (datetime.utcnow() + jwt_settings.ACCESS_TOKEN_LIFETIME)

            response.set_cookie(
                cookie_name,
                request.data['refresh'],
                expires=token_expiration,
                secure=cookie_secure,
                httponly=cookie_httponly,
                samesite=cookie_samesite,
            )

            response.data['access_token_expiration'] = token_expiration

        return response`

Then in urls we would register this endpoint if JWT_AUTH_COOKIE is enabled

`path('token/refresh/', CustomTokenRefreshView.as_view(), name='token_refresh'),`

Let me know what you think, I know its a bit of a grey area as the functionality should be in SimpleJWT. The same could be said about the JWT token cookie but that has been implemented in dj-rest-auth so there is no real reason this can't be.

**Comment by iMerica** [comment]
Can you rebase with latest origin/master? Otherwise I can close this PR and submit another one with your commits in tact.

**Comment by iMerica** [comment]
I decided to just merge a new one so that we can cut a release today. Big thanks for submitting this one @Wolf-Byte !

**Comment by iMerica** [comment]
This contribution is included in the most recent release (2.1.1)

https://pypi.org/project/dj-rest-auth/2.1.1/

Thanks again!

P.S, the refresh view was also recently merged separately in #173

**Comment by Wolf-Byte** [comment]
@iMerica Thanks for adding this.

**Pull request closed without merging**
