### PR TITLE
Fix no context in serializer issue

### PR DESCRIPTION
**Pull request by Helenyin123**
Fix bugs for views couldn't be found in SocialLoginSerializer. The SocialLoginSerializer need context.

### CODE REVIEW

**Comment by iMerica** [comment]
Hi @Helenyin123,

Can you tell me about the issue this is intended to fix? What steps can I take to reproduce it?

**Comment by Helenyin123** [comment]
When using SocialLoginView, the SocialLoginSerializer will send error "View is not defined, pass it as context variable". This is because the view info is not passed in context. You could reproduce by using django-rest-auth SocialLoginView and combine with django-allauth provider adapter. 
Screen Shot 2020-10-25 at 5 00 13 PM

**Comment by Helenyin123** [comment]
Hi Michael, 

I found that I messed up django-rest-auth and dj-rest-auth. I closed this request.

**Comment by yourfavouriteuncle** [comment]
@Helenyin123 why does this mess up dj-rest-auth ? It seems like the correct fix.

**Pull request closed without merging**
