### PR TITLE
Auth token fix

### PR DESCRIPTION
**Pull request by steverecio**
Current version deletes auth token on logout. This renders any auth token based API integrations broken after the user logs out.

### CODE REVIEW

**Comment by iMerica** [comment]
Lots of users today are expecting this logout functionality to work as its currently implemented. 

Perhaps you can propose another solution that handles your case and everyone else's?

**Comment by steverecio** [comment]
Just updated this branch with a new setting `REST_AUTH_TOKEN_PERSISTENT` that would allow the user to change the default behavior. I also apologize, this branch has some of my throttle class code. My fork got jumbled up a bit with the new fork. If the #83 is merged first, then it shouldn't be an issue.

**Comment by iMerica** [comment]
In the summary you mention that if a user logs out, their API integrations will also lose access. Wouldn't it be better to issue separate tokens for each integration/app instead of sharing one token for web access and all other access? Like the way Gitlab and Github handle it.

**Comment by steverecio** [comment]
I'm currently using session authentication for my web app and auth tokens for my API. My original plan was to use a library like you mentioned but DRF auth tokens are one-to-one with the user object ([source](https://github.com/encode/django-rest-framework/blob/master/rest_framework/authtoken/models.py#L14)).

Do you have a library recommendation? This seems like the preferred built-in way to use API keys but I'm open to suggestions.

**Comment by iMerica** [comment]
Hi @steverecio,

Apologies for the delay. Have you considered using [Knox](http://james1345.github.io/django-rest-knox/) ? It allows for multiple tokens per user. I can't think of a reason why also using JWT tokens would not work since they are stateless.

**Comment by iMerica** [comment]
Hi @steverecio,

After some consideration I think think this approach adds yet another flag to solve a problem that can be solved more elegantly using JWTs (JWTs are stateless so you can issue multiple per user and blacklist independently). Given that I'm going to close this PR. 

Apologies for the run around and the big delay!

Michael

**Pull request closed without merging**
