### PR TITLE
attribute check handled to avoid exception during module import

### LINKED ISSUE #181: USER_DETAILS_SERIALIZER setting not being detected
I have a custom user model in my project and thus would also like a custom user serializer. To do this, I have added the following lines in my `settings.py`:
```python
REST_AUTH_SERIALIZERS = {
    "USER_DETAILS_SERIALIZER": "apps.custom_users.serializers.CustomUserSerializer"
}
```
Upon running my project, I'm getting the following error:
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 64, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/config/urls.py", line 32, in <module>
    path('dj-rest-auth/', include('dj_rest_auth.urls')),
  File "/usr/local/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/dj_rest_auth/urls.py", line 1, in <module>
    from dj_rest_auth.views import (LoginView, LogoutView, PasswordChangeView,
  File "/usr/local/lib/python3.8/site-packages/dj_rest_auth/views.py", line 16, in <module>
    from .app_settings import (JWTSerializer, JWTSerializerWithExpiration, LoginSerializer,
  File "/usr/local/lib/python3.8/site-packages/dj_rest_auth/app_settings.py", line 1, in <module>
    from dj_rest_auth.serializers import JWTSerializer as DefaultJWTSerializer
  File "/usr/local/lib/python3.8/site-packages/dj_rest_auth/serializers.py", line 145, in <module>
    class UserDetailsSerializer(serializers.ModelSerializer):
  File "/usr/local/lib/python3.8/site-packages/dj_rest_auth/serializers.py", line 149, in UserDetailsSerializer
    class Meta:
  File "/usr/local/lib/python3.8/site-packages/dj_rest_auth/serializers.py", line 151, in Meta
    fields = ('pk', UserModel.USERNAME_FIELD, UserModel.EMAIL_FIELD, 'first_name', 'last_name')
AttributeError: type object 'CustomUser' has no attribute 'EMAIL_FIELD'
```
It looks like this error is coming from the `dj_rest_auth.serializers.UserDetailsSerializer` class, so it seems to me like it is completely ignoring my setting. Am I formatting the setting wrong or is there something else going on?

### PR DESCRIPTION
**Pull request by jerinpetergeorge**
Fixes #181

### CODE REVIEW

**Comment by Luctia** [comment]
Thanks for this! I do see that you've left in `first_name` and `last_name`. While I haven't tested this, I expect this will result in a similar error described in #181.

**Comment by jerinpetergeorge** [comment]
During module initialization, Python evaluated the `UserModel.USERNAME_FIELD` statement and it couldn't find an attribute named `USERNAME_FIELD` and hence the error. Arbitrary you can add anything to the `field` section of the serializer and Django/DRF will not raise any exceptions unless the serializer instance initialized or evaluated.

So, here (afaik) Django will not raise any exceptions during module loading. @Luctia

**Comment by iMerica** [comment]
👍

**Comment by jerinpetergeorge** [comment]
@iMerica I think we should do a patch release of this, coz I feel this is a *_critical_* one :wink:

**Comment by iMerica** [comment]
2.1.2 is now out. Thank you!

https://pypi.org/project/dj-rest-auth/

**Comment by jerinpetergeorge** [comment]
Hi @Luctia, now you can upgrade the *dj-rest-auth* package and I hope it won't trouble you this time :)

**Pull request merged**
